sudo: require

language: node_js

services:
  - docker

env:
  global:
    - DOCKER_IMAGE="forhot2000/ci"
    - DOCKER_TAG="${TRAVIS_BRANCH//\//_}.${TRAVIS_BUILD_NUMBER}"

before_install:
  - node -v; npm -v
  - docker version
  - echo "docker image $DOCKER_IMAGE:$DOCKER_TAG"

install:
  - npm install
  - docker pull node:0.10-onbuild

before_script:
  - docker images; docker ps -a

script:
  - npm test
  - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker run -d --name ci -p 3000:3000 $DOCKER_IMAGE:$DOCKER_TAG; sleep 10
  - docker ps -n 1; docker logs ci
  - curl --retry 10 --retry-delay 5 -v http://localhost:3000

deploy:
  - provider: script
    script: echo hello staging
    on:
      branch: develop
  - provider: script
    script: echo hello production
    on:
      branch: master
