sudo: require

language: node_js

services:
  - docker

before_install:
  - node -v; npm -v

install:
  - npm install
  - docker pull node:0.10-onbuild

before_script:
  - docker images; docker ps -a

script:
  - npm test
  - docker build -t custom/ci .
  - docker run -d --name ci custom/ci; sleep 10
  - docker ps -n 1; docker logs ci
